/**
 * Interactive setup for CLI credentials
 * Prompts user for missing environment variables and saves to .env
 */

import { createInterface } from "readline";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

interface Credentials {
  WORKFLOWY_USERNAME?: string;
  WORKFLOWY_API_KEY?: string;
  DROPBOX_APP_KEY?: string;
  DROPBOX_APP_SECRET?: string;
  DROPBOX_REFRESH_TOKEN?: string;
  ANTHROPIC_API_KEY?: string;
}

const ENV_PATH = join(process.cwd(), ".env");

function prompt(question: string, hidden = false): Promise<string> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function parseEnvFile(path: string): Credentials {
  if (!existsSync(path)) return {};

  const content = readFileSync(path, "utf-8");
  const creds: Credentials = {};

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const match = trimmed.match(/^([A-Z_]+)=(.*)$/);
    if (match) {
      const [, key, value] = match;
      (creds as Record<string, string>)[key] = value;
    }
  }

  return creds;
}

function writeEnvFile(path: string, creds: Credentials): void {
  const lines: string[] = [
    "# Workflowy MCP Server Configuration",
    "# Generated by setup wizard",
    "",
    "# Workflowy credentials (required)",
    `WORKFLOWY_USERNAME=${creds.WORKFLOWY_USERNAME || ""}`,
    `WORKFLOWY_API_KEY=${creds.WORKFLOWY_API_KEY || ""}`,
    "",
  ];

  if (creds.DROPBOX_APP_KEY || creds.DROPBOX_APP_SECRET || creds.DROPBOX_REFRESH_TOKEN) {
    lines.push(
      "# Dropbox configuration for image hosting (optional)",
      `DROPBOX_APP_KEY=${creds.DROPBOX_APP_KEY || ""}`,
      `DROPBOX_APP_SECRET=${creds.DROPBOX_APP_SECRET || ""}`,
      `DROPBOX_REFRESH_TOKEN=${creds.DROPBOX_REFRESH_TOKEN || ""}`,
      ""
    );
  }

  if (creds.ANTHROPIC_API_KEY) {
    lines.push(
      "# Anthropic API for Claude auto concept extraction (optional)",
      `ANTHROPIC_API_KEY=${creds.ANTHROPIC_API_KEY}`,
      ""
    );
  }

  writeFileSync(path, lines.join("\n"));
}

export async function ensureCredentials(): Promise<boolean> {
  // Load existing credentials
  let creds = parseEnvFile(ENV_PATH);
  let modified = false;

  // Check required credentials
  const hasWorkflowy = creds.WORKFLOWY_USERNAME && creds.WORKFLOWY_API_KEY;

  if (!hasWorkflowy) {
    console.log("\n🔧 First-time setup - Workflowy credentials required\n");

    if (!creds.WORKFLOWY_USERNAME) {
      creds.WORKFLOWY_USERNAME = await prompt("Workflowy email: ");
      modified = true;
    }

    if (!creds.WORKFLOWY_API_KEY) {
      console.log("\nGet your API key at: https://workflowy.com/api-key");
      creds.WORKFLOWY_API_KEY = await prompt("Workflowy API key: ");
      modified = true;
    }
  }

  // Check optional Anthropic key for --auto
  if (!creds.ANTHROPIC_API_KEY) {
    console.log("\n📝 Optional: Anthropic API key enables --auto concept extraction");
    const setupAnthropic = await prompt("Set up Anthropic API key? (y/N): ");

    if (setupAnthropic.toLowerCase() === "y") {
      console.log("\nGet your API key at: https://console.anthropic.com/settings/keys");
      creds.ANTHROPIC_API_KEY = await prompt("Anthropic API key (sk-ant-...): ");
      modified = true;
    }
  }

  // Save if modified
  if (modified) {
    writeEnvFile(ENV_PATH, creds);
    console.log(`\n✅ Credentials saved to ${ENV_PATH}\n`);

    // Reload into process.env
    for (const [key, value] of Object.entries(creds)) {
      if (value) process.env[key] = value;
    }
  }

  // Validate required credentials exist
  if (!creds.WORKFLOWY_USERNAME || !creds.WORKFLOWY_API_KEY) {
    console.error("❌ Workflowy credentials are required");
    return false;
  }

  return true;
}

export async function runSetup(): Promise<void> {
  console.log("\n🔧 Workflowy Concept Map CLI Setup\n");
  console.log("This wizard will configure your credentials.\n");

  let creds = parseEnvFile(ENV_PATH);

  // Workflowy (required)
  console.log("── Workflowy (required) ──");
  creds.WORKFLOWY_USERNAME = await prompt(
    `Email [${creds.WORKFLOWY_USERNAME || "not set"}]: `
  ) || creds.WORKFLOWY_USERNAME;

  console.log("Get your API key at: https://workflowy.com/api-key");
  const newWorkflowyKey = await prompt(
    `API key [${creds.WORKFLOWY_API_KEY ? "****" + creds.WORKFLOWY_API_KEY.slice(-4) : "not set"}]: `
  );
  if (newWorkflowyKey) creds.WORKFLOWY_API_KEY = newWorkflowyKey;

  // Anthropic (optional)
  console.log("\n── Anthropic API (optional, for --auto) ──");
  console.log("Get your API key at: https://console.anthropic.com/settings/keys");
  const newAnthropicKey = await prompt(
    `API key [${creds.ANTHROPIC_API_KEY ? "****" + creds.ANTHROPIC_API_KEY.slice(-4) : "not set"}]: `
  );
  if (newAnthropicKey) creds.ANTHROPIC_API_KEY = newAnthropicKey;

  // Dropbox (optional)
  console.log("\n── Dropbox (optional, for MCP server image hosting) ──");
  const setupDropbox = await prompt("Configure Dropbox? (y/N): ");

  if (setupDropbox.toLowerCase() === "y") {
    console.log("Create an app at: https://www.dropbox.com/developers/apps");
    creds.DROPBOX_APP_KEY = await prompt(
      `App key [${creds.DROPBOX_APP_KEY || "not set"}]: `
    ) || creds.DROPBOX_APP_KEY;

    creds.DROPBOX_APP_SECRET = await prompt(
      `App secret [${creds.DROPBOX_APP_SECRET ? "****" : "not set"}]: `
    ) || creds.DROPBOX_APP_SECRET;

    creds.DROPBOX_REFRESH_TOKEN = await prompt(
      `Refresh token [${creds.DROPBOX_REFRESH_TOKEN ? "****" : "not set"}]: `
    ) || creds.DROPBOX_REFRESH_TOKEN;
  }

  // Save
  writeEnvFile(ENV_PATH, creds);
  console.log(`\n✅ Configuration saved to ${ENV_PATH}\n`);
}
